# Generated by Django 3.2.5 on 2021-08-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WatchList',
                'verbose_name_plural': 'WatchLists',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=' ', max_length=128)),
                ('Broker', models.CharField(choices=[('Alice Blue', 'Alice Blue'), ('Angel Broking', 'Angel Broking'), ('Fyers', 'Fyers'), ('Upstox', 'Upstox'), ('Zerodha', 'Zerodha')], max_length=15)),
                ('UserId', models.CharField(max_length=128)),
                ('Password', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Pin_2FA', models.CharField(max_length=128)),
                ('API_Key', models.CharField(max_length=256)),
                ('API_Secret', models.CharField(max_length=256)),
                ('SubWebHook', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User List',
                'verbose_name_plural': 'User Lists',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.CharField(max_length=200)),
                ('Date', models.DateTimeField()),
                ('Type', models.CharField(choices=[('Buy', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('Regular', models.BooleanField(blank=True, default=False, null=True)),
                ('CO', models.BooleanField(blank=True, default=False, null=True)),
                ('BO', models.BooleanField(blank=True, default=False, null=True)),
                ('AMO', models.BooleanField(blank=True, default=False, null=True)),
                ('InterDay', models.BooleanField(blank=True, default=False, null=True)),
                ('CNC', models.BooleanField(blank=True, default=False, null=True)),
                ('Margin', models.BooleanField(blank=True, default=False, null=True)),
                ('Market', models.BooleanField(blank=True, default=False, null=True)),
                ('Limit', models.BooleanField(blank=True, default=False, null=True)),
                ('Stop', models.BooleanField(blank=True, default=False, null=True)),
                ('StopLimit', models.BooleanField(blank=True, default=False, null=True)),
                ('Validity', models.CharField(choices=[('Day', 'Day'), ('IOC', 'IOC')], max_length=3)),
                ('Price', models.BooleanField(default=True)),
                ('LimitPrice', models.FloatField()),
                ('StopPrice', models.FloatField()),
                ('StopLoss', models.FloatField()),
                ('TakeProfit', models.FloatField()),
                ('TrailingStopLoss', models.FloatField()),
                ('Quantity', models.PositiveIntegerField()),
                ('DisclosedQuantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActivateCopyTrade', models.BooleanField(default=False)),
                ('Multiplier', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('Users', models.ManyToManyField(to='core.UserList')),
            ],
            options={
                'verbose_name': 'Bucket',
                'verbose_name_plural': 'Buckets',
            },
        ),
    ]
