# Generated by Django 3.2.5 on 2021-07-30 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.CharField(max_length=200)),
                ('Date', models.DateTimeField()),
                ('Type', models.CharField(choices=[('Buy', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('Regular', models.BooleanField(blank=True, default=False, null=True)),
                ('CO', models.BooleanField(blank=True, default=False, null=True)),
                ('BO', models.BooleanField(blank=True, default=False, null=True)),
                ('AMO', models.BooleanField(blank=True, default=False, null=True)),
                ('InterDay', models.BooleanField(blank=True, default=False, null=True)),
                ('CNC', models.BooleanField(blank=True, default=False, null=True)),
                ('Margin', models.BooleanField(blank=True, default=False, null=True)),
                ('Market', models.BooleanField(blank=True, default=False, null=True)),
                ('Limit', models.BooleanField(blank=True, default=False, null=True)),
                ('Stop', models.BooleanField(blank=True, default=False, null=True)),
                ('StopLimit', models.BooleanField(blank=True, default=False, null=True)),
                ('Validity', models.CharField(choices=[('Day', 'Day'), ('IOC', 'IOC')], max_length=3)),
                ('Price', models.BooleanField(default=True)),
                ('LimitPrice', models.FloatField()),
                ('StopPrice', models.FloatField()),
                ('StopLoss', models.FloatField()),
                ('TakeProfit', models.FloatField()),
                ('TrailingStopLoss', models.FloatField()),
                ('Quantity', models.PositiveIntegerField()),
                ('DisclosedQuantity', models.PositiveIntegerField()),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
