# Generated by Django 3.2.5 on 2021-08-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('expiry', models.CharField(max_length=30)),
                ('strike', models.CharField(max_length=30)),
                ('lotsize', models.CharField(max_length=30)),
                ('instrumenttype', models.CharField(max_length=30)),
                ('exch_seg', models.CharField(max_length=30)),
                ('tick_size', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
    ]
