# Generated by Django 3.2.5 on 2021-08-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210805_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bucket'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4),
        ),
    ]
