# Generated by Django 3.2.5 on 2021-08-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210805_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='AMO',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='BO',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='CNC',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='CO',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='InterDay',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Limit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Margin',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Market',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Regular',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Stop',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='StopLimit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ValidityDay',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ValidityIOC',
        ),
        migrations.AddField(
            model_name='transaction',
            name='AdvanceProductType',
            field=models.CharField(choices=[('Intraday', 'Intraday'), ('CNC', 'CNC'), ('Margin', 'Margin')], default='Intraday', max_length=8),
        ),
        migrations.AddField(
            model_name='transaction',
            name='OrderType',
            field=models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit'), ('Stop', 'Stop'), ('Stop Limit', 'Stop Limit')], default='Market', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ProductType',
            field=models.CharField(choices=[('Regular', 'Regular'), ('CO', 'CO'), ('BO', 'BO'), ('AMO', 'AMO')], default='Regular', max_length=7),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Validity',
            field=models.CharField(choices=[('Day', 'Day'), ('IOC', 'IOC')], default='Day', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4),
        ),
    ]
