# Generated by Django 3.2.5 on 2021-08-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210816_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Bucket',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='User',
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
