# Generated by Django 3.2.5 on 2021-08-17 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20210816_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.CharField(max_length=200)),
                ('Date', models.DateTimeField()),
                ('Type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('ProductType', models.CharField(choices=[('Regular', 'Regular'), ('CO', 'CO'), ('BO', 'BO'), ('AMO', 'AMO')], default='Regular', max_length=7)),
                ('AdvanceProductType', models.CharField(choices=[('Intraday', 'Intraday'), ('CNC', 'CNC'), ('Margin', 'Margin')], default='Intraday', max_length=8)),
                ('OrderType', models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit'), ('Stop', 'Stop'), ('Stop Limit', 'Stop Limit')], default='Market', max_length=10)),
                ('Validity', models.CharField(choices=[('Day', 'Day'), ('IOC', 'IOC')], default='Day', max_length=3)),
                ('Price', models.BooleanField(default=True)),
                ('LimitPrice', models.FloatField(blank=True, null=True)),
                ('StopPrice', models.FloatField(blank=True, null=True)),
                ('StopLoss', models.FloatField(blank=True, null=True)),
                ('TakeProfit', models.FloatField(blank=True, null=True)),
                ('TrailingStopLoss', models.FloatField(blank=True, null=True)),
                ('Quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('DisclosedQuantity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Bucket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bucket')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
